//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchOutFrom
    {
        public string BatchOutForm_ID { get; set; }
        public System.DateTime BtachOut_DT { get; set; }
        public string KnifeDetail_ID { get; set; }
        public string BatchOut_Emp_ID { get; set; }
        public string BatchConfirm_EmpID { get; set; }
        public string BatchOutForm_Create_DT { get; set; }
        public string BatchOutForm_Create_ID { get; set; }
        public string BatchOutForm_Modify_DT { get; set; }
        public string BatchOutForm_Modify_ID { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
