//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabin
    {
        public string Cabin_ID { get; set; }
        public string Cabin_Type { get; set; }
        public string Cabin_Location { get; set; }
        public System.DateTime Cabin_Create_DT { get; set; }
        public string Cabin_Create_ID { get; set; }
        public Nullable<System.DateTime> Cabin_Modify_DT { get; set; }
        public string Cabin_Modify_ID { get; set; }
    }
}
