//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNC_ALARM_Log
    {
        public decimal Sno { get; set; }
        public string CNC_IP { get; set; }
        public string Create_DT { get; set; }
        public string CNC_ALARM_CODE { get; set; }
        public string CNC_ALARM_MSG { get; set; }
        public string CNC_Lang { get; set; }
        public System.DateTime CNC_ALARM_DT { get; set; }
        public string CNC_ModeType { get; set; }
        public string CNC_OperationNo { get; set; }
        public string CNC_EditNo { get; set; }
        public string CNC_Screen { get; set; }
        public string CNC__Coordinate_X { get; set; }
        public string CNC_Distance_X { get; set; }
        public string CNC_Coordinate_Y { get; set; }
        public string CNC_Distance_Y { get; set; }
        public string CNC_Coordinate_Z { get; set; }
        public string CNC_Distance_Z { get; set; }
        public string CNC_KnifeCabin { get; set; }
        public string CNC_RunProgramBank { get; set; }
        public string CNC_Compensate_H { get; set; }
        public string CNC_Compensate_X { get; set; }
        public string CNC_Compensate_Y { get; set; }
        public string CNC_Compensate_Z { get; set; }
        public string CNC_ATCTL_ID { get; set; }
        public string CNC_Return_Speed { get; set; }
        public string CNC_Fast_Feed { get; set; }
        public string CNC_Cutting_Feed { get; set; }
        public string CNC_Spindle_Feed { get; set; }
        public string CNC_Feed_Type { get; set; }
        public string CNC_Door_Status { get; set; }
        public string CNC_Door_Interlock { get; set; }
    
        public virtual CNC CNC { get; set; }
    }
}
