//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNCDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNCDetail()
        {
            this.CNCKnifeLists = new HashSet<CNCKnifeList>();
        }
    
        public string CNCDetail_ID { get; set; }
        public string CNCMaster_ID { get; set; }
        public string CNCDetail_IP { get; set; }
        public string CNCDetail_Version { get; set; }
        public string CNCDetail_Status { get; set; }
        public System.DateTime CNCDetail_Create_DT { get; set; }
        public string CNCDetail_Create_ID { get; set; }
        public Nullable<System.DateTime> CNCDetail_Modify_DT { get; set; }
        public string CNCDetail_Modify_ID { get; set; }
    
        public virtual CNCMaster CNCMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCKnifeList> CNCKnifeLists { get; set; }
    }
}
