//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNCMonitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNCMonitor()
        {
            this.CNC_ALARM_Log = new HashSet<CNC_ALARM_Log>();
            this.CNC_ATCTL_Log = new HashSet<CNC_ATCTL_Log>();
            this.CNC_PRD3_Log = new HashSet<CNC_PRD3_Log>();
            this.CNC_Ver_Log = new HashSet<CNC_Ver_Log>();
            this.CNC_WKCNTR_Log = new HashSet<CNC_WKCNTR_Log>();
        }
    
        public string CNC_IP { get; set; }
        public string Create_DT { get; set; }
        public string CNCDetail_ID { get; set; }
        public string CNC_Status { get; set; }
        public Nullable<long> CNC_Current_ProductionAmount { get; set; }
        public string CNC_RunTime { get; set; }
        public string CNC_StayTime { get; set; }
        public string CNC_CloseTime { get; set; }
        public string CNC_ErrTime { get; set; }
        public string CNC_StopTime { get; set; }
        public string CNC_Ver { get; set; }
        public string CNC_Model { get; set; }
        public Nullable<long> CNC_Alert_ProductionAmount { get; set; }
        public Nullable<long> CNC_End_ProductionAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_ALARM_Log> CNC_ALARM_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_ATCTL_Log> CNC_ATCTL_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_PRD3_Log> CNC_PRD3_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_Ver_Log> CNC_Ver_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_WKCNTR_Log> CNC_WKCNTR_Log { get; set; }
    }
}
