//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNCMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNCMaster()
        {
            this.CNCDetails = new HashSet<CNCDetail>();
        }
    
        public string CNCMaster_ID { get; set; }
        public string CNC_Name { get; set; }
        public string CNC_Brand { get; set; }
        public long CNC_Quality { get; set; }
        public System.DateTime CNCMaster_Create_DT { get; set; }
        public string CNCMaster_Create_ID { get; set; }
        public Nullable<System.DateTime> CNCMaster_Modify_DT { get; set; }
        public string CNCMaster_Modify_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCDetail> CNCDetails { get; set; }
    }
}
