//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collet2Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collet2Master()
        {
            this.Collet2Detail = new HashSet<Collet2Detail>();
        }
    
        public string Collet2Master_ID { get; set; }
        public string Collet2_Name { get; set; }
        public string Collet2_Brand { get; set; }
        public string Collet2_Spec { get; set; }
        public string Collet2_CabinID { get; set; }
        public long Collet2_Quality { get; set; }
        public string Collet2Master_Create_ID { get; set; }
        public System.DateTime Collet2Master_Create_DT { get; set; }
        public string Collet2Master_Modify_ID { get; set; }
        public System.DateTime Collet2Master_Modify_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collet2Detail> Collet2Detail { get; set; }
    }
}
