//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiltMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HiltMaster()
        {
            this.HiltDetails = new HashSet<HiltDetail>();
        }
    
        public string HiltMaster_ID { get; set; }
        public string Hilt_Name { get; set; }
        public string Hilt_Brand { get; set; }
        public string Hilt_Spec { get; set; }
        public string Hilt_CabinID { get; set; }
        public long Hilt_Quality { get; set; }
        public System.DateTime HiltMaster_Create_DT { get; set; }
        public string HiltMaster_Create_ID { get; set; }
        public System.DateTime HiltMaster_Modify_DT { get; set; }
        public string HiltMaster_Modify_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiltDetail> HiltDetails { get; set; }
    }
}
