//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiltDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HiltDetail()
        {
            this.StockDetails = new HashSet<StockDetail>();
            this.KnifeLists = new HashSet<KnifeList>();
        }
    
        public string HiltDetail_ID { get; set; }
        public string HiltMaster_ID { get; set; }
        public string HiltDetail_Status { get; set; }
        public string IsNewHilt { get; set; }
        public System.DateTime NewEnter_DT { get; set; }
        public System.DateTime HiltDetail_Create_DT { get; set; }
        public string HiltDetail_Create_ID { get; set; }
        public System.DateTime HiltDetail_Modify_DT { get; set; }
        public string HiltDetail_Modify_ID { get; set; }
    
        public virtual HiltMaster HiltMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KnifeList> KnifeLists { get; set; }
    }
}
