//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnifeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KnifeDetail()
        {
            this.CNC_ATCTL_Log = new HashSet<CNC_ATCTL_Log>();
            this.KnifeUseLogs = new HashSet<KnifeUseLog>();
            this.StockDetails = new HashSet<StockDetail>();
            this.KnifeLists = new HashSet<KnifeList>();
        }
    
        public string KnifeDetail_ID { get; set; }
        public string KnifeMaster_ID { get; set; }
        public string IsNewKnife { get; set; }
        public System.DateTime NewEnter_DT { get; set; }
        public string KnifeDetail_Status { get; set; }
        public System.DateTime KnifeDetail_Create_DT { get; set; }
        public string KnifeDetail_Create_ID { get; set; }
        public System.DateTime KnifeDetail_Modify_DT { get; set; }
        public string KnifeDetail_Modify_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNC_ATCTL_Log> CNC_ATCTL_Log { get; set; }
        public virtual KnifeMaster KnifeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KnifeUseLog> KnifeUseLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KnifeList> KnifeLists { get; set; }
    }
}
