//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnifeUseLog
    {
        public string KnifeUseLog_ID { get; set; }
        public string KnifeDetail_ID { get; set; }
        public System.DateTime Knife_Use_BeginDT { get; set; }
        public System.DateTime Knife_Use_EndDT { get; set; }
        public long Knife_Use_Time { get; set; }
        public System.DateTime KnifeUseLog_Create_DT { get; set; }
        public string KnifeUseLog_Create_ID { get; set; }
        public Nullable<System.DateTime> KnifeUseLog_Modify_DT { get; set; }
        public string KnifeUseLog_Modify_ID { get; set; }
    
        public virtual KnifeDetail KnifeDetail { get; set; }
    }
}
