//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasureDetail()
        {
            this.KnifeLists = new HashSet<KnifeList>();
            this.StockDetails = new HashSet<StockDetail>();
        }
    
        public string MeasureDetail_ID { get; set; }
        public string MeasureMaster_ID { get; set; }
        public string MeasureDetail_Status { get; set; }
        public System.DateTime MeasureDetail_Create_DT { get; set; }
        public string MeasureDetail_Create_ID { get; set; }
        public System.DateTime MeasureDetail_Modify_DT { get; set; }
        public string MeasureDetail_Modify_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KnifeList> KnifeLists { get; set; }
        public virtual MeasureMaster MeasureMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
    }
}
