//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NailMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NailMaster()
        {
            this.NailDetails = new HashSet<NailDetail>();
        }
    
        public string NailMaster_ID { get; set; }
        public string Nail_Name { get; set; }
        public string Nail_Brand { get; set; }
        public string Nail_Spec { get; set; }
        public string Nail_CabinID { get; set; }
        public long Nail_Quality { get; set; }
        public string NailMaster_Create_ID { get; set; }
        public System.DateTime NailMaster_Create_DT { get; set; }
        public string NailMaster_Modify_ID { get; set; }
        public System.DateTime NailMaster_Modify_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NailDetail> NailDetails { get; set; }
    }
}
