//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NutMaster()
        {
            this.NutDetails = new HashSet<NutDetail>();
        }
    
        public string NutMaster_ID { get; set; }
        public string Nut_Name { get; set; }
        public string Nut_Brand { get; set; }
        public string Nut_Spec { get; set; }
        public long Nut_Quality { get; set; }
        public string Nut_CabinID { get; set; }
        public System.DateTime NutMaster_Create_DT { get; set; }
        public string NutMaster_Create_ID { get; set; }
        public System.DateTime NutMaster_Modify_DT { get; set; }
        public string NutMaster_Modify_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutDetail> NutDetails { get; set; }
    }
}
