//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDetail()
        {
            this.Informs = new HashSet<Inform>();
            this.KnifeChangeFroms = new HashSet<KnifeChangeFrom>();
            this.OutFroms = new HashSet<OutFrom>();
        }
    
        public long Sno { get; set; }
        public string Master_ID { get; set; }
        public string Detail_ID { get; set; }
        public string MasterID_Type { get; set; }
        public long Bound_Type { get; set; }
        public System.DateTime Create_DT { get; set; }
        public string Memo { get; set; }
    
        public virtual Collet1Detail Collet1Detail { get; set; }
        public virtual Collet2Detail Collet2Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inform> Informs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KnifeChangeFrom> KnifeChangeFroms { get; set; }
        public virtual KnifeDetail KnifeDetail { get; set; }
        public virtual MeasureDetail MeasureDetail { get; set; }
        public virtual NailDetail NailDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutFrom> OutFroms { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual HiltDetail HiltDetail { get; set; }
    }
}
