//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKnifeInForm
    {
        public string Inform_ID { get; set; }
        public string Master_ID { get; set; }
        public string In_EmpID { get; set; }
        public string Confirm_EmpID { get; set; }
        public Nullable<int> InForm_Quality { get; set; }
        public string Knife_Name { get; set; }
        public string unit { get; set; }
        public string DetailID_Status { get; set; }
        public string DetailID_UseTime { get; set; }
    }
}
