//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductionPlan
    {
        public string Good_Name { get; set; }
        public decimal Planning_ID { get; set; }
        public Nullable<decimal> CNCKnifeList_ID { get; set; }
        public string Class_Type { get; set; }
        public string Class_EmpID { get; set; }
        public int Class_StandardPerson { get; set; }
        public int Class_RealPerson { get; set; }
        public System.DateTime Planning_Create_DT { get; set; }
        public string Model_Name { get; set; }
        public string WorkStation_No { get; set; }
        public string Model_ID { get; set; }
        public string Good_ID { get; set; }
        public string Planning_Create_ID { get; set; }
        public System.DateTime Planning_Modify_DT { get; set; }
        public string Planning_Modify_ID { get; set; }
        public string KnifeList_ID { get; set; }
    }
}
