//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inform
    {
        public string Inform_ID { get; set; }
        public string Detail_ID { get; set; }
        public string Detail_Status { get; set; }
        public string Inform_Create_ID { get; set; }
        public System.DateTime Inform_Create_DT { get; set; }
        public string Inform_Modify_ID { get; set; }
        public System.DateTime Inform_Modify_DT { get; set; }
        public string DetailID_Type { get; set; }
        public System.DateTime In_DT { get; set; }
        public string In_EmpID { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual StockDetail StockDetail { get; set; }
    }
}
