//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnifeChangeFrom
    {
        public string KnifeChangeForm_ID { get; set; }
        public string OrgKnifeDetail_ID { get; set; }
        public System.DateTime KnifeChange_DT { get; set; }
        public string KnifeDetail_ID { get; set; }
        public string KnifeChanger_EmpID { get; set; }
        public string KnifeChanger_Reslut { get; set; }
        public string KnifeConfirm_EmpID { get; set; }
        public string OrgKnifeDetail_Status { get; set; }
        public System.DateTime KnifeChangeForm_Create_DT { get; set; }
        public string KnifeChangeForm_Create_ID { get; set; }
        public Nullable<System.DateTime> KnifeChangeForm_Modify_DT { get; set; }
        public string KnifeChangeForm_Modify_ID { get; set; }
        public string DetailID_Type { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual StockDetail StockDetail { get; set; }
    }
}
