//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasureMaster()
        {
            this.MeasureDetails = new HashSet<MeasureDetail>();
        }
    
        public string MeasureMaster_ID { get; set; }
        public string Measure_Name { get; set; }
        public string Measure_Spec { get; set; }
        public string Measure_Brand { get; set; }
        public string Measure_CabinID { get; set; }
        public long Measure_Quality { get; set; }
        public string MeasureMaster_Create_ID { get; set; }
        public Nullable<System.DateTime> MeasureMaster_Create_DT { get; set; }
        public string MeasureMaster_Modify_ID { get; set; }
        public Nullable<System.DateTime> MeasureMaster_Modify_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasureDetail> MeasureDetails { get; set; }
    }
}
