//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCNC_Alarm_Log
    {
        public string CNC_IP { get; set; }
        public decimal Sno { get; set; }
        public string Create_DT { get; set; }
        public string CNC_ALARM_CODE { get; set; }
        public string CNC_ALARM_MSG { get; set; }
        public System.DateTime CNC_ALARM_DT { get; set; }
        public string CNC_OperationNo { get; set; }
    }
}
